/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AppStore: typeof import('./stores/index').AppStore
  const ArticleStore: typeof import('./stores/modules/article').ArticleStore
  const HomeStore: typeof import('./stores/modules/home').HomeStore
  const RootContext: typeof import('./stores/index').RootContext
  const createRef: typeof import('react').createRef
  const createStore: typeof import('./stores/index').createStore
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const observer: typeof import('mobx-react-lite').observer
  const startTransition: typeof import('react').startTransition
  const useAutoScroll: typeof import('./hooks/useAutoScroll').useAutoScroll
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useHref: typeof import('react-router').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router').useNavigate
  const useNavigationType: typeof import('react-router').useNavigationType
  const useOutlet: typeof import('react-router').useOutlet
  const useOutletContext: typeof import('react-router').useOutletContext
  const useParams: typeof import('react-router').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router').useResolvedPath
  const useRoutes: typeof import('react-router').useRoutes
  const useState: typeof import('react').useState
  const useStore: typeof import('./stores/index').useStore
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { AppStore, PrefetchStore } from './stores/index'
  import('./stores/index')
  // @ts-ignore
  export type { ArticleStore } from './stores/modules/article'
  import('./stores/modules/article')
  // @ts-ignore
  export type { HomeStore } from './stores/modules/home'
  import('./stores/modules/home')
}
